### ISSUE TITLE
Support project.json / xproj

### ISSUE THREAD

**Issue by vcsjones** [smiggleworth/Stripe.Client#12]
Now might be a good time to consider supporting multiple TFMs.

This brings about a few significant changes.
- MSTest needs to go. xUnit all the things.
- `Project.json` needs to get added.

It might be worth waiting until RC2 drops before making significant progress on this.

**Comment by vcsjones** [comment]
I took a small stab at this over at 08f3c8b. It focuses purely on the `Stripe.Client.Sdk` project.

It ported over quite nicely, with a few notes.
- The project.json file is currently set up to support .NET Framework 4.5 and 4.6, so it keeps parity with its existing supported frameworks.
- The .NET Platform framework is now supported, so it will work xplat and be supported in DNX / DOTNET projects.

A few things did not port over and required small changes.
- Some `using` declarations were removed since they weren't being used, and supporting them would require increasing the number of dependencies.
- `GetTypeCode` is not supported in the CoreFx. It was replaced with some simple type checks.
- `ConfigurationManager` is gone in the CoreFx. For the .NETFramework TFMs, this functionality was left in place so it is not a breaking change. However, for CoreFx, the `AppSettingsConfiguration` is unavailable with the assumption that `StripeConfiguration` would be used instead. This seems like a cleaner approach in general because it does not force the consumer to place their configuration in a specific location.

Overall it looks like moving to project.json and supporting Core is fairly easy, for the main SDK. The unit tests remain a challenge, and AutoFac support in DNX remains an unknown to me.

**Comment by smiggleworth** [comment]
Awesome work

**Comment by vcsjones** [comment]
I have migrated unit tests over to xunit with 8ba4fee2f98f98b24621a5bd39ebbb0be1ac711b. DNX `1.0.0-rc1-update1` is required. RC2 is not supported yet as Xunit doesn't support it yet, either. The unit test runner in Visual Studio 2015 supports everything as well, assuming you also have Update 1 installed for Visual Studio. Finally, the unit tests do not support coreclr, as NSubstitute does not have a nuget package available to support it.

All of the tests pass except for the ignored ones.

Thinking long term, my goal is to keep this branch up-to-date with your work and up to date as the CoreFx continues to get updated. Eventually once it RTWs I'll make a proper pull request out of it.

To run the unit tests by CLI, you can use `dnx test`.

**Comment by vcsjones** [comment]
I should probably point out some of the changes required to get the tests to work.
- A test was using `System.Web`. That had to go, so I pulled in an appropriate package instead for parsing query strings.
-  `TestMethod` -> `Fact`.
- There are no class-level decorators in Xunit, for the most part.
- Xunit has no "SetUp" attribute concept. It instead suggests you use a constructor to prepare your fixture. Xunit tries to steer people away from this kind of statefulness because tests are executed in parallel.

**Comment by smiggleworth** [comment]
upgrading to .net standard.
